---
- name: CodeDeploy Agentインストール状態確認
  shell: rpm -qa codedeploy-agent
  register: codedeploy_package
  check_mode: no
  changed_when: false
  failed_when: false

- name: CodeDeploy Agentインストール
  shell: bash -lc "cd /tmp && wget https://aws-codedeploy-ap-northeast-1.s3.amazonaws.com/latest/install && chmod +x ./install && ./install auto"
  when: codedeploy_package.stdout == ""

- name: CodeDeploy Agentサービス定義ファイルのパーミッション変更
  file:
    path: /usr/lib/systemd/system/codedeploy-agent.service
    owner: root
    group: root
    mode: 0644

- name: CodeDeploy Agentの設定ファイル配置
  template:
    src: codedeployagent.yml.j2
    dest: /etc/codedeploy-agent/conf/codedeployagent.yml
    owner: root
    group: root
    mode: 0644

- name: CodeDeploy Agentサービス登録
  service:
    name: codedeploy-agent
    enabled: yes
    state: started