---
- name: create Amazon Web Services
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - iam
    - ec2
  tasks:
    - name: Refresh inventory
      meta: refresh_inventory

- name: build sbapp
  hosts: tag_Name_<<ec2 name as filter>>
  user: ec2-user
  become: True
  gather_facts: true
  roles:
    - yum
    - java11
